language: node__js
deploy:
  provider: gae
  keyfile: secrets.json
  project: kengru-do
  on: master
before_install:
- openssl aes-256-cbc -K $encrypted_04145aa3abce_key -iv $encrypted_04145aa3abce_iv
  -in secrets.json.enc -out secrets.json -d
