language: node_js
node_js:
  - "10"
  - "9"
  - "8"
  - "7"
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm test
deploy:
  provider: gae
  keyfile: gae-secret.json
  project: kengru-do
  on: master
before_install:
- openssl aes-256-cbc -K $encrypted_c5644d2faee2_key -iv $encrypted_c5644d2faee2_iv
  -in gae-secret.json.enc -out gae-secret.json -d
