services:
  kengru-do:
    image: localhost:5000/kengru-do:latest
    container_name: kengru-do
    restart: unless-stopped
    environment:
      - ADMIN_PASS=${ADMIN_PASS}
    ports:
      - "42069:42069"
    networks:
      - proxy
      - internal
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  proxy:
    external: true
  internal:
    external: true
